services:
  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "6000:6000"
      - "8080:8080"
    env_file:
      - ./server/.env
    volumes:
      - ./server/public/uploads:/usr/src/app/public/uploads
    restart: always

  # Frontend Service
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.baselearn.in
      - NEXT_PUBLIC_BACKEND_URL=https://api.baselearn.in
      - API_PROXY_TARGET=http://backend:5000
    depends_on:
      - backend
    restart: always
